# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc2a37e5f754706d2bc6b9f28c1ed7ef8b90827bea697f2c26731c59ece15ecebe8271dd8484ede8fa7ec69b8d7fe2596defa0d040373bb817cab0650baa927f

test:
  secret_key_base: 7ab4fa2286190408f36fd64535dc00bda96afa7eccfaf1de457471403b702997802ec181e123004595c1890d4567d2f9647899abe08d4924af36eed88743f4a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
